name: medi_1
description: A real-time ambulance tracking and alert app.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.11.0
  geolocator: ^13.0.3
  http: ^1.3.0
  flutter_polyline_points: ^2.1.0
  location:
  geocoding:
  shared_preferences: ^2.5.3
  image_picker:
  path_provider:
  cupertino_icons: ^1.0.8
  google_places_autocomplete_text_field: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons:
  flutter_native_splash:

flutter_icons:
  android: true
  image_path: "assets/logo.png"
flutter_native_splash:
  color: "#ffffff"
  image: assets/logo.png
  branding: assets/brand_text.png
  background_image: assets/splash_bg.png
  android_gravity: center
  fullscreen: true


# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/user_icon.png
    - assets/ambulance.png
    - assets/user_avatar.png
    - assets/logo.png
    - assets/splash_bg.png